//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DYJXCEntities : DbContext
    {
        public DYJXCEntities()
            : base("name=DYJXCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_BarCodeLabel> t_BarCodeLabel { get; set; }
        public virtual DbSet<t_BarCodeLabelDetail> t_BarCodeLabelDetail { get; set; }
        public virtual DbSet<t_CPInBillDetail> t_CPInBillDetail { get; set; }
        public virtual DbSet<t_CPInBillHeader> t_CPInBillHeader { get; set; }
        public virtual DbSet<t_CPInBillOFXiMa> t_CPInBillOFXiMa { get; set; }
        public virtual DbSet<t_CPOutBillDetail> t_CPOutBillDetail { get; set; }
        public virtual DbSet<t_CPOutBillHeader> t_CPOutBillHeader { get; set; }
        public virtual DbSet<t_OutWhouseDetail> t_OutWhouseDetail { get; set; }
        public virtual DbSet<t_OutWhouseHeader> t_OutWhouseHeader { get; set; }
        public virtual DbSet<t_CPOutBillOfXiMa> t_CPOutBillOfXiMa { get; set; }
        public virtual DbSet<t_InWhouseDetail> t_InWhouseDetail { get; set; }
        public virtual DbSet<t_InWhouseHeader> t_InWhouseHeader { get; set; }
    }
}
