//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formtable_main_84
    {
        public int id { get; set; }
        public Nullable<int> requestId { get; set; }
        public string lcbh { get; set; }
        public Nullable<int> sqgs { get; set; }
        public Nullable<int> jbbm { get; set; }
        public Nullable<int> jbr { get; set; }
        public string sqrq { get; set; }
        public string htjf { get; set; }
        public string htyf { get; set; }
        public string htbd { get; set; }
        public string fkfs { get; set; }
        public Nullable<decimal> htzje { get; set; }
        public string xmcgspd { get; set; }
        public string yshzspd { get; set; }
        public string xjd { get; set; }
        public string yjb { get; set; }
        public string htfj { get; set; }
        public string fjsc { get; set; }
        public string xglc { get; set; }
        public string xgwd { get; set; }
        public string sfhs { get; set; }
        public Nullable<int> htzsl { get; set; }
        public Nullable<decimal> htzsl2 { get; set; }
        public string cght { get; set; }
        public string JSFS { get; set; }
        public string DeliveryStart { get; set; }
        public string DeliveryEnd { get; set; }
    }
}
