//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modeDataShare_5_set
    {
        public int id { get; set; }
        public Nullable<int> sourceid { get; set; }
        public Nullable<int> righttype { get; set; }
        public Nullable<int> sharetype { get; set; }
        public Nullable<int> relatedid { get; set; }
        public Nullable<int> rolelevel { get; set; }
        public Nullable<int> showlevel { get; set; }
        public Nullable<int> isdefault { get; set; }
        public Nullable<int> layoutid { get; set; }
        public Nullable<int> layoutid1 { get; set; }
        public Nullable<int> layoutorder { get; set; }
        public Nullable<int> isrolelimited { get; set; }
        public Nullable<int> rolefieldtype { get; set; }
        public Nullable<int> rolefield { get; set; }
        public Nullable<int> higherlevel { get; set; }
        public Nullable<int> rightid { get; set; }
        public Nullable<int> requestid { get; set; }
        public Nullable<int> showlevel2 { get; set; }
        public Nullable<int> hrmCompanyVirtualType { get; set; }
        public Nullable<int> orgrelation { get; set; }
        public Nullable<int> joblevel { get; set; }
        public string jobleveltext { get; set; }
        public string SETUUID { get; set; }
    }
}
