//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modeDataShare_5
    {
        public int id { get; set; }
        public Nullable<int> sourceid { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> content { get; set; }
        public Nullable<int> seclevel { get; set; }
        public Nullable<int> sharelevel { get; set; }
        public Nullable<int> srcfrom { get; set; }
        public Nullable<int> opuser { get; set; }
        public Nullable<int> isDefault { get; set; }
        public Nullable<int> layoutid { get; set; }
        public Nullable<int> layoutid1 { get; set; }
        public Nullable<int> layoutorder { get; set; }
        public Nullable<int> sharesetid { get; set; }
        public Nullable<int> higherlevel { get; set; }
        public Nullable<int> setid { get; set; }
        public Nullable<int> rightid { get; set; }
        public Nullable<int> requestid { get; set; }
        public Nullable<int> showlevel2 { get; set; }
        public Nullable<int> joblevel { get; set; }
        public string jobleveltext { get; set; }
    }
}
