//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_BarCodeLabel
    {
        public int FRecID { get; set; }
        public string FBillNo { get; set; }
        public string FMDNo { get; set; }
        public Nullable<System.DateTime> FBillDate { get; set; }
        public string FState { get; set; }
        public Nullable<int> FPrintNum { get; set; }
        public string FMatCode { get; set; }
        public int FCstCode { get; set; }
        public int FShaPiID { get; set; }
        public int FZhiChang { get; set; }
        public string FMachine { get; set; }
        public string FBathNo { get; set; }
        public string FColor { get; set; }
        public string FCarNo { get; set; }
        public Nullable<decimal> FTotalWeight { get; set; }
        public string FunitName { get; set; }
        public Nullable<int> FNum { get; set; }
        public Nullable<int> FJGType { get; set; }
        public string FFirstChecher { get; set; }
        public Nullable<System.DateTime> FFirstCheckDate { get; set; }
        public string FSecondChecker { get; set; }
        public Nullable<System.DateTime> FSecondCheckDate { get; set; }
        public string FCreator { get; set; }
        public Nullable<System.DateTime> FCreateDate { get; set; }
        public string FCompany { get; set; }
        public string FModMan { get; set; }
        public Nullable<System.DateTime> FModDate { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string FInFlag { get; set; }
    }
}
