//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CPOutBillHeader
    {
        public int FID { get; set; }
        public string FBillNo { get; set; }
        public System.DateTime FBillDate { get; set; }
        public string FBiller { get; set; }
        public string FChecker { get; set; }
        public string FCheckDate { get; set; }
        public string FCheckState { get; set; }
        public Nullable<int> FDepID { get; set; }
        public Nullable<int> FMangerID { get; set; }
        public Nullable<int> FQCMan { get; set; }
        public Nullable<int> FOutOperMan { get; set; }
        public string FSecChecker { get; set; }
        public string FSecCheckDate { get; set; }
        public string FSecCheckState { get; set; }
        public string FThirdChecker { get; set; }
        public string FThirdCheckDate { get; set; }
        public string FThirdCheckState { get; set; }
        public Nullable<int> FCstCode { get; set; }
        public string FCstAddress { get; set; }
        public string FJHAddress { get; set; }
        public Nullable<int> FBillType { get; set; }
        public Nullable<int> FSaleType { get; set; }
        public Nullable<int> FPlayType { get; set; }
        public string FPBName { get; set; }
        public string FJD { get; set; }
        public string FZT { get; set; }
        public string FJZ { get; set; }
        public string FCarNo { get; set; }
        public string FOrderNo { get; set; }
        public string FFoundNo { get; set; }
        public string FOrderNote { get; set; }
        public string FLost { get; set; }
        public string FAmountType { get; set; }
        public string FMemo { get; set; }
        public string FMatNameForPrint { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public Nullable<decimal> UDF06 { get; set; }
        public Nullable<decimal> UDF07 { get; set; }
        public Nullable<decimal> UDF08 { get; set; }
        public Nullable<decimal> UDF09 { get; set; }
        public Nullable<decimal> UDF10 { get; set; }
    }
}
