//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CPInBillOFXiMa
    {
        public int FID { get; set; }
        public int FPID { get; set; }
        public int FItemID { get; set; }
        public string FGH { get; set; }
        public string FXiMa { get; set; }
        public Nullable<decimal> FWeight { get; set; }
        public Nullable<decimal> FPZ { get; set; }
        public string FMemo { get; set; }
    }
}
