//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_InWhouseDetail
    {
        public int FRecID { get; set; }
        public string FBillNo { get; set; }
        public Nullable<int> FXiMaID { get; set; }
        public Nullable<int> FNum { get; set; }
        public Nullable<decimal> FWeight { get; set; }
        public string FUnitName { get; set; }
        public string FLocationID { get; set; }
        public string FMemo { get; set; }
        public string FOperName { get; set; }
        public string FZhengNum { get; set; }
        public string FAnLun { get; set; }
    }
}
