//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_InWhouseHeader
    {
        public int FRecID { get; set; }
        public string FBillType { get; set; }
        public string FBillNo { get; set; }
        public Nullable<System.DateTime> FBillDate { get; set; }
        public string FStockCode { get; set; }
        public string FBiller { get; set; }
        public string FBillChecker { get; set; }
        public string FCheckDate { get; set; }
        public string FBillStatus { get; set; }
        public Nullable<int> FTotalNum { get; set; }
        public Nullable<decimal> FTotalWeight { get; set; }
        public Nullable<int> FSupplyID { get; set; }
        public string FNote { get; set; }
        public Nullable<int> FManagerID { get; set; }
        public Nullable<int> FYSHManID { get; set; }
        public string FSecChecker { get; set; }
        public string FSecCheckDate { get; set; }
        public string FSecCheckState { get; set; }
        public string FClassNo { get; set; }
        public string FThridChecker { get; set; }
        public string FThridCheckDate { get; set; }
        public string FThridCheckState { get; set; }
    }
}
