//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_OutWhouseDetail
    {
        public int FRecId { get; set; }
        public string FBarCode { get; set; }
        public Nullable<int> FIndex { get; set; }
        public Nullable<decimal> FWeight { get; set; }
        public string FUnitID { get; set; }
        public Nullable<decimal> FNum { get; set; }
        public Nullable<int> FAuxUnitID { get; set; }
        public string FLocationCode { get; set; }
        public string FState { get; set; }
        public string FCreator { get; set; }
        public Nullable<System.DateTime> FCreateDate { get; set; }
        public string FModMan { get; set; }
        public Nullable<System.DateTime> FModDate { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public Nullable<decimal> UDF06 { get; set; }
        public Nullable<decimal> UDF07 { get; set; }
        public Nullable<decimal> UDF08 { get; set; }
        public Nullable<decimal> UDF09 { get; set; }
        public Nullable<decimal> UDF10 { get; set; }
    }
}
