//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_OutWhouseHeader
    {
        public int FRecID { get; set; }
        public string FBillType { get; set; }
        public string FBillNo { get; set; }
        public Nullable<System.DateTime> FBillDate { get; set; }
        public string FStockCode { get; set; }
        public string FBiller { get; set; }
        public string FBillChecker { get; set; }
        public string FCheckDate { get; set; }
        public string FBillStatus { get; set; }
        public int FTotalNum { get; set; }
        public decimal FTotalWeight { get; set; }
        public int FPlanTotalNum { get; set; }
        public decimal FPlanTotalWeight { get; set; }
        public Nullable<int> FSupplyID { get; set; }
        public string FNote { get; set; }
        public Nullable<int> FManagerID { get; set; }
        public Nullable<int> FYSHManID { get; set; }
        public string FZhiChang { get; set; }
        public string FItemID { get; set; }
        public string FLotNo { get; set; }
        public Nullable<int> FShaPi { get; set; }
        public string FMachine { get; set; }
        public string FSourceBillNo { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public Nullable<decimal> UDF06 { get; set; }
        public Nullable<decimal> UDF07 { get; set; }
        public Nullable<decimal> UDF08 { get; set; }
        public Nullable<decimal> UDF09 { get; set; }
        public Nullable<decimal> UDF10 { get; set; }
        public string FReturnCustName { get; set; }
    }
}
