//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uf_zh_PurchaseOrder
    {
        public int id { get; set; }
        public Nullable<int> requestId { get; set; }
        public string Cg_no { get; set; }
        public string company { get; set; }
        public string Sup_no { get; set; }
        public string Sup_name { get; set; }
        public string Pay_type { get; set; }
        public string Ship_addr { get; set; }
        public Nullable<int> formmodeid { get; set; }
        public Nullable<int> modedatacreater { get; set; }
        public Nullable<int> modedatacreatertype { get; set; }
        public string modedatacreatedate { get; set; }
        public string modedatacreatetime { get; set; }
        public string Sup_fullname { get; set; }
        public string DeliveryStart { get; set; }
        public string DeliveryEnd { get; set; }
        public string JSFS { get; set; }
    }
}
