//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uf_zh_PurchaseOrder_dt1
    {
        public int id { get; set; }
        public Nullable<int> mainid { get; set; }
        public string Cg_no { get; set; }
        public string Mat_id { get; set; }
        public string Mat_name { get; set; }
        public string color { get; set; }
        public string Col_code { get; set; }
        public string quantity { get; set; }
        public string price { get; set; }
        public string Pack_price { get; set; }
        public string Delivery { get; set; }
    }
}
